from __future__ import annotations

import os
from pathlib import Path


BACKEND_ROOT = Path(__file__).resolve().parent
PROJECT_ROOT = BACKEND_ROOT.parent
STATIC_ROOT = BACKEND_ROOT / "static"
SCENE_ROOT = Path(os.environ.get("HKU_RT_SCENE_ROOT", str(PROJECT_ROOT / "HKU_scenes"))).resolve()
SCENE_XML = SCENE_ROOT / "scenario_HKU.xml"
MESH_ROOT = SCENE_ROOT / "meshes"
BUNDLE_ROOT = SCENE_ROOT / "cache" / "render_bundles"

HOST = os.environ.get("HKU_RT_HOST", "0.0.0.0")
PORT = int(os.environ.get("HKU_RT_PORT", "8090"))

DEFAULT_FREQUENCY_HZ = float(os.environ.get("HKU_RT_DEFAULT_FREQUENCY_HZ", "3500000000"))
DEFAULT_MAX_DEPTH = int(os.environ.get("HKU_RT_DEFAULT_MAX_DEPTH", "4"))
DEFAULT_LINK_SAMPLES = int(os.environ.get("HKU_RT_DEFAULT_LINK_SAMPLES", "30000"))
DEFAULT_LINK_MAX_NUM_PATHS_PER_SRC = int(os.environ.get("HKU_RT_DEFAULT_LINK_MAX_NUM_PATHS_PER_SRC", "1000000"))
DEFAULT_RADIOMAP_SAMPLES = int(os.environ.get("HKU_RT_DEFAULT_RADIOMAP_SAMPLES", "1000000"))
MIN_FREQUENCY_HZ = float(os.environ.get("HKU_RT_MIN_FREQUENCY_HZ", "100000000"))
MAX_FREQUENCY_HZ = float(os.environ.get("HKU_RT_MAX_FREQUENCY_HZ", "100000000000"))
MIN_SOLVER_DEPTH = int(os.environ.get("HKU_RT_MIN_SOLVER_DEPTH", "1"))
MAX_SOLVER_DEPTH = int(os.environ.get("HKU_RT_MAX_SOLVER_DEPTH", "8"))
MIN_LINK_SAMPLES = int(os.environ.get("HKU_RT_MIN_LINK_SAMPLES", "1"))
MAX_LINK_SAMPLES = int(os.environ.get("HKU_RT_MAX_LINK_SAMPLES", "1000000"))
MIN_LINK_MAX_NUM_PATHS_PER_SRC = int(os.environ.get("HKU_RT_MIN_LINK_MAX_NUM_PATHS_PER_SRC", "1"))
MAX_LINK_MAX_NUM_PATHS_PER_SRC = int(os.environ.get("HKU_RT_MAX_LINK_MAX_NUM_PATHS_PER_SRC", "1000000"))
MIN_LINK_TAP_INDEX = int(os.environ.get("HKU_RT_MIN_LINK_TAP_INDEX", "-4096"))
MAX_LINK_TAP_INDEX = int(os.environ.get("HKU_RT_MAX_LINK_TAP_INDEX", "4096"))
MAX_LINK_TAP_COUNT = int(os.environ.get("HKU_RT_MAX_LINK_TAP_COUNT", "256"))
MIN_LINK_FFT_SIZE = int(os.environ.get("HKU_RT_MIN_LINK_FFT_SIZE", "16"))
MAX_LINK_FFT_SIZE = int(os.environ.get("HKU_RT_MAX_LINK_FFT_SIZE", "8192"))
MIN_LINK_SUBCARRIER_SPACING_HZ = float(os.environ.get("HKU_RT_MIN_LINK_SUBCARRIER_SPACING_HZ", "1000"))
MAX_LINK_SUBCARRIER_SPACING_HZ = float(os.environ.get("HKU_RT_MAX_LINK_SUBCARRIER_SPACING_HZ", "1000000000"))
MIN_RADIOMAP_SAMPLES = int(os.environ.get("HKU_RT_MIN_RADIOMAP_SAMPLES", "1"))
MAX_RADIOMAP_SAMPLES = int(os.environ.get("HKU_RT_MAX_RADIOMAP_SAMPLES", "2000000"))
MAX_RADIOMAP_EFFECTIVE_SAMPLES = int(os.environ.get("HKU_RT_MAX_RADIOMAP_EFFECTIVE_SAMPLES", "32000000"))
MAX_RADIOMAP_CELLS = int(os.environ.get("HKU_RT_MAX_RADIOMAP_CELLS", "100000"))
MIN_RADIOMAP_CELL_SIZE = float(os.environ.get("HKU_RT_MIN_RADIOMAP_CELL_SIZE", "0.01"))
MAX_RADIOMAP_CELL_SIZE = float(os.environ.get("HKU_RT_MAX_RADIOMAP_CELL_SIZE", "100.0"))
MIN_RADIOMAP_DENSITY_LEVEL = int(os.environ.get("HKU_RT_MIN_RADIOMAP_DENSITY_LEVEL", "1"))
MAX_RADIOMAP_DENSITY_LEVEL = int(os.environ.get("HKU_RT_MAX_RADIOMAP_DENSITY_LEVEL", "3"))
MIN_SOLVER_SEED = int(os.environ.get("HKU_RT_MIN_SOLVER_SEED", "0"))
MAX_SOLVER_SEED = int(os.environ.get("HKU_RT_MAX_SOLVER_SEED", str((2 ** 32) - 1)))
RADIOMAP_MAX_PENDING_JOBS = int(os.environ.get("HKU_RT_RADIOMAP_MAX_PENDING_JOBS", "8"))
RADIOMAP_MAX_STORED_JOBS = int(os.environ.get("HKU_RT_RADIOMAP_MAX_STORED_JOBS", "64"))
RADIOMAP_JOB_TTL_SECONDS = float(os.environ.get("HKU_RT_RADIOMAP_JOB_TTL_SECONDS", "7200"))
MOBILITY_MAX_PENDING_JOBS = int(os.environ.get("HKU_RT_MOBILITY_MAX_PENDING_JOBS", "4"))
MOBILITY_MAX_STORED_JOBS = int(os.environ.get("HKU_RT_MOBILITY_MAX_STORED_JOBS", "32"))
MOBILITY_JOB_TTL_SECONDS = float(os.environ.get("HKU_RT_MOBILITY_JOB_TTL_SECONDS", "7200"))
DEEPMIMO_ENV_PYTHON = os.environ.get(
    "HKU_RT_DEEPMIMO_ENV_PYTHON",
    "/home/defaultuser/venvs/env_hku_rt_gpu/bin/python",
)
GENERATED_ROOT = Path(os.environ.get("HKU_RT_GENERATED_ROOT", str(PROJECT_ROOT / "generated"))).resolve()
DEEPMIMO_JOB_ROOT = Path(os.environ.get("HKU_RT_DEEPMIMO_JOB_ROOT", str(GENERATED_ROOT / "deepmimo_jobs"))).resolve()
DEEPMIMO_MAX_PENDING_JOBS = int(os.environ.get("HKU_RT_DEEPMIMO_MAX_PENDING_JOBS", "2"))
DEEPMIMO_MAX_STORED_JOBS = int(os.environ.get("HKU_RT_DEEPMIMO_MAX_STORED_JOBS", "16"))
DEEPMIMO_JOB_TTL_SECONDS = float(os.environ.get("HKU_RT_DEEPMIMO_JOB_TTL_SECONDS", "86400"))
DEEPMIMO_MAX_RECEIVERS = int(os.environ.get("HKU_RT_DEEPMIMO_MAX_RECEIVERS", "200000"))
DEEPMIMO_DEFAULT_CHUNK_SIZE = int(os.environ.get("HKU_RT_DEEPMIMO_DEFAULT_CHUNK_SIZE", "1024"))
DEEPMIMO_MIN_GRID_SPACING = float(os.environ.get("HKU_RT_DEEPMIMO_MIN_GRID_SPACING", "0.25"))
DEEPMIMO_MAX_GRID_SPACING = float(os.environ.get("HKU_RT_DEEPMIMO_MAX_GRID_SPACING", "100.0"))
DEEPMIMO_CONVERT_SCENE_GEOMETRY = os.environ.get("HKU_RT_DEEPMIMO_CONVERT_SCENE_GEOMETRY", "0").strip().lower() in {
    "1",
    "true",
    "yes",
    "on",
}
RADIOMAP_MEASUREMENT_MATERIAL = os.environ.get("HKU_RT_RADIOMAP_MEASUREMENT_MATERIAL", "itu_medium_dry_ground")
MIN_ANTENNA_ARRAY_ROWS = int(os.environ.get("HKU_RT_MIN_ANTENNA_ARRAY_ROWS", "1"))
MAX_ANTENNA_ARRAY_ROWS = int(os.environ.get("HKU_RT_MAX_ANTENNA_ARRAY_ROWS", "16"))
MIN_ANTENNA_ARRAY_COLS = int(os.environ.get("HKU_RT_MIN_ANTENNA_ARRAY_COLS", "1"))
MAX_ANTENNA_ARRAY_COLS = int(os.environ.get("HKU_RT_MAX_ANTENNA_ARRAY_COLS", "16"))
MAX_ANTENNA_ARRAY_ELEMENTS = int(os.environ.get("HKU_RT_MAX_ANTENNA_ARRAY_ELEMENTS", "256"))
MIN_ANTENNA_ARRAY_SPACING = float(os.environ.get("HKU_RT_MIN_ANTENNA_ARRAY_SPACING", "0.01"))
MAX_ANTENNA_ARRAY_SPACING = float(os.environ.get("HKU_RT_MAX_ANTENNA_ARRAY_SPACING", "10.0"))

DEFAULT_TX_POSITION = (72.0, 37.0, 40.0)
DEFAULT_RX_POSITION = (90.0, 52.0, 1.5)
DEFAULT_RADIOMAP_SIZE = (160.0, 160.0)
DEFAULT_RADIOMAP_HEIGHT_OFFSET = 1.5
DEFAULT_RADIOMAP_DENSITY_LEVEL = 2
DEFAULT_LINK_TAPS_L_MIN = int(os.environ.get("HKU_RT_DEFAULT_LINK_TAPS_L_MIN", "0"))
DEFAULT_LINK_TAPS_L_MAX = int(os.environ.get("HKU_RT_DEFAULT_LINK_TAPS_L_MAX", "100"))
DEFAULT_LINK_TAPS_FFT_SIZE = int(os.environ.get("HKU_RT_DEFAULT_LINK_TAPS_FFT_SIZE", "512"))
DEFAULT_LINK_TAPS_SUBCARRIER_SPACING_HZ = float(os.environ.get("HKU_RT_DEFAULT_LINK_TAPS_SUBCARRIER_SPACING_HZ", "30000"))
DEFAULT_ANTENNA_ARRAY_NUM_ROWS = int(os.environ.get("HKU_RT_DEFAULT_ANTENNA_ARRAY_NUM_ROWS", "1"))
DEFAULT_ANTENNA_ARRAY_NUM_COLS = int(os.environ.get("HKU_RT_DEFAULT_ANTENNA_ARRAY_NUM_COLS", "1"))
DEFAULT_ANTENNA_ARRAY_VERTICAL_SPACING = float(os.environ.get("HKU_RT_DEFAULT_ANTENNA_ARRAY_VERTICAL_SPACING", "0.5"))
DEFAULT_ANTENNA_ARRAY_HORIZONTAL_SPACING = float(os.environ.get("HKU_RT_DEFAULT_ANTENNA_ARRAY_HORIZONTAL_SPACING", "0.5"))
DEFAULT_ANTENNA_ARRAY_PATTERN = os.environ.get("HKU_RT_DEFAULT_ANTENNA_ARRAY_PATTERN", "iso")
DEFAULT_ANTENNA_ARRAY_POLARIZATION = os.environ.get("HKU_RT_DEFAULT_ANTENNA_ARRAY_POLARIZATION", "V")
MIN_MOBILITY_WAYPOINTS = int(os.environ.get("HKU_RT_MIN_MOBILITY_WAYPOINTS", "2"))
MAX_MOBILITY_WAYPOINTS = int(os.environ.get("HKU_RT_MAX_MOBILITY_WAYPOINTS", "32"))
MIN_MOBILITY_VELOCITY_MPS = float(os.environ.get("HKU_RT_MIN_MOBILITY_VELOCITY_MPS", "0.1"))
MAX_MOBILITY_VELOCITY_MPS = float(os.environ.get("HKU_RT_MAX_MOBILITY_VELOCITY_MPS", "30.0"))
MIN_MOBILITY_TIME_STEP_S = float(os.environ.get("HKU_RT_MIN_MOBILITY_TIME_STEP_S", "0.1"))
MAX_MOBILITY_TIME_STEP_S = float(os.environ.get("HKU_RT_MAX_MOBILITY_TIME_STEP_S", "10.0"))
MIN_MOBILITY_STEPS = int(os.environ.get("HKU_RT_MIN_MOBILITY_STEPS", "2"))
DEFAULT_MOBILITY_MAX_STEPS = int(os.environ.get("HKU_RT_DEFAULT_MOBILITY_MAX_STEPS", "50"))
MAX_MOBILITY_STEPS = int(os.environ.get("HKU_RT_MAX_MOBILITY_STEPS", "500"))
