from __future__ import annotations

from pathlib import Path
import unittest


PROJECT_ROOT = Path(__file__).resolve().parents[1]


def read_static_js(name: str) -> str:
    return (PROJECT_ROOT / "backend" / "static" / "js" / name).read_text(encoding="utf-8")


def read_static_css(name: str) -> str:
    return (PROJECT_ROOT / "backend" / "static" / "css" / name).read_text(encoding="utf-8")


class FrontendRegressionTests(unittest.TestCase):
    def test_entry_search_focus_does_not_reset_selection_badge(self) -> None:
        source = read_static_js("entry_map.js")

        self.assertNotIn("updateEntryMapBadge(tileId)", source)
        self.assertIn("syncEntryOverviewUi();\n    setEntrySearchHint(`Located in", source)

    def test_loaded_tile_status_requires_all_tile_bundles(self) -> None:
        source = read_static_js("viewer.js")

        self.assertIn("this.tileBundleCounts = new Map();", source)
        self.assertIn("this.tileExpectedBundleCounts = new Map();", source)
        self.assertIn("loadedCount === expectedCount", source)
        self.assertNotIn("loadedTileIds.add(bundle.tile)", source)

    def test_rt_capabilities_are_loaded_for_antenna_arrays(self) -> None:
        api_source = read_static_js("api.js")
        app_source = read_static_js("app.js")
        state_source = read_static_js("app_state.js")

        self.assertIn('requestJson("/api/rt/capabilities")', api_source)
        self.assertIn("state.rtCapabilities = await getRtCapabilities();", app_source)
        self.assertIn("solverControls.applyRtCapabilities(state.rtCapabilities);", app_source)
        self.assertIn("txArray: createDefaultAntennaArray()", state_source)
        self.assertIn("rxArray: createDefaultAntennaArray()", state_source)

    def test_antenna_array_payloads_are_sent_to_solvers(self) -> None:
        source = read_static_js("solver_controls.js")
        html = (PROJECT_ROOT / "backend" / "static" / "index.html").read_text(encoding="utf-8")

        self.assertIn("tx_array: antennaArrayPayload(state.antenna.txArray)", source)
        self.assertIn("rx_array: antennaArrayPayload(state.antenna.rxArray)", source)
        self.assertIn("...commonSolverConfig(),\n      samples_per_tx", source)
        self.assertIn("samples_per_tx: state.radiomap.solver.samplesPerTx", source)
        self.assertIn('id="txArrayPattern"', html)
        self.assertIn('id="rxArrayPattern"', html)
        self.assertIn('class="paramField linkOnlyParam" for="rxArrayPattern"', html)

    def test_radiomap_ui_parameters_are_wired(self) -> None:
        source = read_static_js("solver_controls.js")
        viewer_source = read_static_js("viewer.js")
        colormap_source = read_static_js("colormaps.js")
        html = (PROJECT_ROOT / "backend" / "static" / "index.html").read_text(encoding="utf-8")
        state_source = read_static_js("app_state.js")
        dom_source = read_static_js("dom_refs.js")

        self.assertIn('id="rmSamplesPerTx"', html)
        self.assertIn('id="rmCellSize"', html)
        self.assertIn('id="rmColormap"', html)
        self.assertIn('id="rmColorbarSection"', html)
        self.assertIn('id="radiomapResolutionSection"', html)
        self.assertIn('id="rmMesh"', html)
        self.assertIn('id="rmArea"', html)
        self.assertIn('id="rmCellSizeSummary"', html)
        self.assertIn("Solver Mesh", html)
        self.assertIn("Resolution &amp; Budget", html)
        self.assertIn("Display Scale", html)
        self.assertIn('<option value="jet" selected>jet</option>', html)
        self.assertIn("solver: {\n      samplesPerTx: 1000000", state_source)
        self.assertIn('colormap: "jet"', state_source)
        self.assertIn('rmSamplesPerTx: document.getElementById("rmSamplesPerTx")', dom_source)
        self.assertIn('rmMesh: document.getElementById("rmMesh")', dom_source)
        self.assertIn('rmCellSizeSummary: document.getElementById("rmCellSizeSummary")', dom_source)
        self.assertIn("surface.cell_size = state.radiomap.surface.cellSize", source)
        self.assertIn("samples_per_tx: state.radiomap.solver.samplesPerTx", source)
        self.assertNotIn("samples_per_tx: 1000000", source)
        self.assertNotIn("state.livePreview.radiomap", source)
        self.assertNotIn("function scheduleRadiomapPreview", source)
        self.assertNotIn("function runRadiomapLiveJob", source)
        self.assertIn('throw new Error(job.error || job.message || "Radio map job failed");', source)
        self.assertIn('surface.resolution_mode === "cell_size_grid"', source)
        self.assertIn('`${nx} x ${ny} cells (${formatCount(surface.grid_cell_count)})`', source)
        self.assertIn("surface.triangle_count", source)
        self.assertIn("colormapGradient(colormap)", source)
        self.assertIn('Colormap: ${colormap}', source)
        self.assertIn('Display limits: ${minDb.toFixed(0)} .. ${maxDb.toFixed(0)} dB', source)
        self.assertIn('import {colorForColormap} from "/js/colormaps.js";', viewer_source)
        self.assertIn("colorForColormap(colormap, t)", viewer_source)
        self.assertIn('colormap: "jet"', viewer_source)
        self.assertIn('? name : "jet"', colormap_source)

    def test_radiomap_results_live_in_right_side_dock(self) -> None:
        html = (PROJECT_ROOT / "backend" / "static" / "index.html").read_text(encoding="utf-8")
        css_source = read_static_css("app.css")
        source = read_static_js("solver_controls.js")
        app_source = read_static_js("app.js")
        state_source = read_static_js("app_state.js")
        dom_source = read_static_js("dom_refs.js")
        scene_source = read_static_js("scene_render_state.js")

        dock_start = html.index('id="linkChannelSection"')
        link_panel_start = html.index('id="linkPanel"')
        radiomap_panel_start = html.index('id="radiomapPanel"')
        dock_html = html[dock_start:link_panel_start]
        left_panel_html = html[link_panel_start:]

        self.assertIn('id="radiomapResult"', dock_html)
        self.assertIn('id="btnResultDockToggle"', dock_html)
        self.assertIn('aria-expanded="true"', dock_html)
        self.assertIn('id="channelAnalysisScroll" class="channelAnalysisScroll"', dock_html)
        self.assertIn(".channelAnalysisDock{position:absolute;", css_source)
        self.assertIn("backdrop-filter:blur(14px);overflow:hidden;transition:", css_source)
        self.assertIn(".channelAnalysisScroll{box-sizing:border-box;max-height:calc(100vh - var(--analysis-dock-top) - 18px - 62px);overflow-x:hidden;overflow-y:auto;padding:0 12px 12px;scrollbar-width:thin;", css_source)
        self.assertIn(".channelAnalysisDock.collapsed .channelAnalysisScroll{max-height:0;padding-top:0;padding-bottom:0;opacity:0;overflow:hidden;pointer-events:none}", css_source)
        self.assertIn(".channelAnalysisDock.collapsed .channelAnalysisChevron{transform:rotate(-90deg)}", css_source)
        self.assertIn(".channelAnalysisScroll::-webkit-scrollbar{width:6px}", css_source)
        self.assertIn(".channelAnalysisScroll::-webkit-scrollbar-thumb:hover", css_source)
        self.assertNotIn(".channelAnalysisDock::-webkit-scrollbar", css_source)
        self.assertIn("resultDock: {\n    expanded: true,", state_source)
        self.assertIn('btnResultDockToggle: document.getElementById("btnResultDockToggle")', dom_source)
        self.assertIn('channelAnalysisScroll: document.getElementById("channelAnalysisScroll")', dom_source)
        self.assertIn('ui.btnResultDockToggle.addEventListener("click", () => {', app_source)
        self.assertIn("state.resultDock.expanded = !state.resultDock.expanded;", app_source)
        self.assertIn("function syncResultDockUi()", scene_source)
        self.assertIn('ui.linkChannelSection.classList.toggle("collapsed", !expanded);', scene_source)
        self.assertIn("ui.channelAnalysisScroll.inert = !expanded;", scene_source)
        self.assertIn("Radio Map Results", source)
        self.assertIn("Path gain / Terrain grid", source)
        self.assertIn("Path gain (dB)", html)
        self.assertIn("Grid", html)
        self.assertIn("Solver Mesh", html)
        self.assertIn("Area", html)
        self.assertIn("Cell Size", html)
        self.assertIn("Samples / Tx", html)
        self.assertIn("Result Range", html)
        self.assertIn("Display Scale", html)
        self.assertNotIn('id="radiomapResult"', left_panel_html[left_panel_html.index('id="radiomapPanel"'):])
        self.assertIn('ui.radiomapResult.style.display = "none";', source)
        self.assertIn('ui.linkChannelSection.classList.remove("hidden");', source)
        self.assertIn('ui.resultDockTitle.textContent = "Radio Map Results";', source)
        self.assertIn('syncModeUi();\n  syncControlSidebarUi();\n  syncViewerMarkers();', scene_source)
        self.assertIn('syncPerformanceUi();\n  syncResultDockUi();', scene_source)
        self.assertIn('button.removeAttribute("aria-busy");\n    sceneRenderState.renderAll();', app_source)

    def test_live_preview_controls_and_schedulers_are_wired(self) -> None:
        html = (PROJECT_ROOT / "backend" / "static" / "index.html").read_text(encoding="utf-8")
        app_source = read_static_js("app.js")
        api_source = read_static_js("api.js")
        dom_source = read_static_js("dom_refs.js")
        scene_source = read_static_js("scene_render_state.js")
        solver_source = read_static_js("solver_controls.js")
        state_source = read_static_js("app_state.js")
        viewer_source = read_static_js("viewer.js")
        css_source = read_static_css("app.css")

        self.assertIn('id="livePreviewStatus"', html)
        self.assertIn('id="livePreviewEnabled" type="checkbox"', html)
        self.assertIn('id="livePreviewLinkSamples"', html)
        self.assertIn('id="livePreviewPathsDelay"', html)
        self.assertNotIn('id="livePreviewRmSamples"', html)
        self.assertNotIn('id="livePreviewRmDelay"', html)
        self.assertNotIn('id="livePreviewRmCellSize"', html)
        self.assertIn('class="devicePrecisionPanel deviceCompactBar hidden"', html)
        self.assertNotIn("devicePrecisionKicker", html)
        self.assertIn('id="devicePrecisionTitle" class="devicePrecisionTitle">Tx</div>', html)
        self.assertIn("Pick a surface point or fine-tune below.", html)
        self.assertIn('id="linkSurfaceClearance"', html)
        self.assertIn('value="1.5"', html)
        self.assertIn(">Clearance\n", html)
        self.assertIn("Distance from the picked surface for Link Tx/Rx and Radio Map Tx", html)
        self.assertIn(".deviceDock{position:absolute;left:50%;bottom:16px;z-index:17;width:auto;max-width:min(600px, calc(100vw - 420px));min-width:0", css_source)
        self.assertIn(".devicePrecisionPanel{width:auto;max-width:100%;", css_source)
        self.assertIn(".deviceCompactBar{display:flex;align-items:center;gap:6px;min-height:44px}", css_source)
        self.assertIn(".devicePrecisionStatus{position:absolute;width:1px;height:1px;overflow:hidden;clip-path:inset(50%);white-space:nowrap}", css_source)
        self.assertIn(".deviceCoordPanels{min-width:0;display:flex;align-items:center;gap:6px;flex:0 1 auto}", css_source)
        self.assertIn(".deviceCoordPanel{min-width:0;flex:0 0 auto}", css_source)
        self.assertIn(".deviceCoordGrid{display:grid;grid-template-columns:repeat(3,104px);gap:5px}", css_source)
        self.assertIn("text-align:left;font-variant-numeric:tabular-nums", css_source)
        self.assertIn(".deviceCoordGrid .unitInput input[type=\"number\"],.deviceClearanceField .unitInput input[type=\"number\"]{padding-right:24px}", css_source)
        self.assertIn(".deviceCoordGrid .unitSuffix,.deviceClearanceField .unitSuffix{right:6px;font-size:10px}", css_source)
        self.assertIn(".deviceClearanceField{display:flex;align-items:center;gap:5px;flex:0 0 166px", css_source)
        self.assertIn(".deviceCompactBar{flex-wrap:wrap;gap:6px}", css_source)
        self.assertIn("livePreview: {\n    enabled: false", state_source)
        self.assertIn("previewSamplesPerSrc: 1000", state_source)
        self.assertIn("surfaceClearanceM: 1.5", state_source)
        self.assertGreaterEqual(state_source.count("surfaceClearanceM: 1.5"), 2)
        self.assertNotIn("mapDelayS: 3.0", state_source)
        self.assertNotIn("previewSamplesPerTx", state_source)
        self.assertIn('livePreviewEnabled: document.getElementById("livePreviewEnabled")', dom_source)
        self.assertIn('linkSurfaceClearance: document.getElementById("linkSurfaceClearance")', dom_source)
        self.assertIn('livePreviewParams: [...document.querySelectorAll(".livePreviewParam")]', dom_source)
        self.assertIn('node.classList.toggle("hidden", !isLink);', scene_source)
        self.assertIn('ui.linkSurfaceClearanceField.classList.toggle("hidden"', scene_source)
        self.assertIn('nextActiveTarget === "rm-tx"', scene_source)
        self.assertIn('? "Rx"\n    : nextActiveTarget === "rm-tx"\n      ? "RM Tx"\n      : "Tx";', scene_source)
        self.assertIn('export function solveLink(payload, options = {})', api_source)
        self.assertIn("signal: options.signal", api_source)

        self.assertIn("function linkSolvePayload({preview = false} = {})", solver_source)
        self.assertIn("solver.samples_per_src = Math.max(1, Math.floor(Number(state.livePreview.link.previewSamplesPerSrc)));", solver_source)
        self.assertIn("solver.max_num_paths_per_src = Math.min(Number(solver.max_num_paths_per_src), 10000);", solver_source)
        self.assertIn("channel.compute_taps = false;", solver_source)
        self.assertIn("new AbortController()", solver_source)
        self.assertIn("token !== live.generation", solver_source)
        self.assertIn("function radiomapJobPayload()", solver_source)
        self.assertIn("density_level: state.radiomap.surface.densityLevel", solver_source)
        self.assertNotIn("Math.max(Number(state.radiomap.surface.cellSize), previewCellSize)", solver_source)
        self.assertNotIn("live.inFlight = true;", solver_source)
        self.assertNotIn("live.pendingPreview = true;", solver_source)
        self.assertNotIn("live.pendingFinal = true;", solver_source)
        self.assertIn("live.previewController?.abort();\n    live.finalController?.abort();", solver_source)
        self.assertIn('setLivePreviewStatus("link", preview ? "Previewing" : "Finalizing");', solver_source)
        self.assertNotIn('setLivePreviewStatus("radiomap"', solver_source)
        self.assertIn("handleLivePreviewDeviceUpdate(target, phase = \"change\")", solver_source)
        self.assertIn("function linkPickPosition(pick)", solver_source)
        self.assertIn("function radiomapTxPickPosition(pick)", solver_source)
        self.assertIn("pick.surfacePosition", solver_source)
        self.assertIn("pick.surfaceNormal", solver_source)
        self.assertIn("state.link.surfaceClearanceM", solver_source)
        self.assertIn("state.radiomap.surfaceClearanceM", solver_source)
        self.assertIn("const position = radiomapTxPickPosition(pick);", solver_source)
        self.assertIn("setLogicalAndVisual(state.radiomap.tx, state.radiomap.txVisual, position);", solver_source)
        self.assertIn("surfacePosition: [hit.point.x, hit.point.y, hit.point.z]", viewer_source)
        self.assertIn("surfaceNormal: surfaceNormal ?", viewer_source)

        self.assertIn("solverControls.cancelLivePreview();\n  state.pickTarget = null;", app_source)
        self.assertIn('view.addEventListener("pointerdown", handlePickPointerDown, {capture: true});', app_source)
        self.assertIn("event.currentTarget.setPointerCapture(event.pointerId);", app_source)
        self.assertIn('document.getElementById("view").releasePointerCapture(event.pointerId);', app_source)
        self.assertIn('solverControls.handleLivePreviewDeviceUpdate(target, livePhase);', app_source)
        self.assertIn('solverControls.handleLivePreviewDeviceUpdate(target, "change");', app_source)
        self.assertIn('[inputs.linkRxX, "link-rx"]', app_source)
        self.assertNotIn('solverControls.handleLivePreviewDeviceUpdate("rm-tx", "change");', app_source)
        self.assertIn('inputs.linkSurfaceClearance.addEventListener("change"', app_source)
        self.assertIn("solverControls.readSurfaceClearanceInput();", app_source)

    def test_path_details_show_array_pair_aggregation(self) -> None:
        source = read_static_js("solver_controls.js")

        self.assertIn('addField("Array Pairs", String(path.array_pair_count ?? 1));', source)
        self.assertIn('addField("Strongest Pair", formatFixed(path.strongest_pair_power_db, 2, " dB"));', source)

    def test_link_results_live_in_right_side_dock(self) -> None:
        html = (PROJECT_ROOT / "backend" / "static" / "index.html").read_text(encoding="utf-8")
        source = read_static_js("solver_controls.js")

        dock_start = html.index('id="linkChannelSection"')
        link_panel_start = html.index('id="linkPanel"')
        radiomap_panel_start = html.index('id="radiomapPanel"')
        dock_html = html[dock_start:link_panel_start]
        link_panel_html = html[link_panel_start:radiomap_panel_start]
        tap_index = dock_html.index('id="linkTapAnalysisSection"')
        selection_index = dock_html.index('id="pathSelectionSection"')
        buttons_index = dock_html.index('id="pathButtons"')

        self.assertIn("Link Results", dock_html)
        self.assertIn('id="linkResult"', dock_html)
        self.assertIn('id="pathSelectionSection"', dock_html)
        self.assertIn('id="pathSelectionCount"', dock_html)
        self.assertIn('id="pathButtons"', dock_html)
        self.assertIn('id="pathDetailSection"', dock_html)
        self.assertIn('id="linkTapAnalysisSection"', dock_html)
        self.assertLess(tap_index, selection_index)
        self.assertLess(selection_index, buttons_index)
        self.assertNotIn('id="linkResult"', link_panel_html)
        self.assertNotIn('id="pathSelectionSection"', link_panel_html)
        self.assertNotIn('id="pathButtons"', link_panel_html)
        self.assertNotIn('id="pathDetailSection"', link_panel_html)
        self.assertNotIn("Channel Result", html)
        self.assertIn("function renderPathSelection(paths, selectedIndex, onSelect)", source)
        self.assertIn('ui.pathSelectionSection.classList.add("hidden");', source)
        self.assertIn('ui.pathSelectionSection.classList.remove("hidden");', source)
        self.assertIn("getViewer().renderPaths(result.paths, index);", source)
        self.assertIn("getViewer().renderPaths(paths, index);", source)

    def test_tap_analysis_no_longer_controls_whole_link_result_dock(self) -> None:
        source = read_static_js("solver_controls.js")
        render_channel = source[
            source.index("function renderLinkChannel"):
            source.index("function renderLinkResult")
        ]

        self.assertIn('ui.linkTapAnalysisSection.classList.add("hidden");', render_channel)
        self.assertIn('ui.linkTapAnalysisSection.classList.remove("hidden");', render_channel)
        self.assertNotIn("ui.linkChannelSection.classList.add", render_channel)
        self.assertNotIn("ui.linkChannelSection.classList.remove", render_channel)

    def test_tap_chart_axes_are_labeled_and_not_clipped(self) -> None:
        source = read_static_js("solver_controls.js")
        html = (PROJECT_ROOT / "backend" / "static" / "index.html").read_text(encoding="utf-8")
        css = (PROJECT_ROOT / "backend" / "static" / "css" / "app.css").read_text(encoding="utf-8")

        self.assertIn('viewBox="0 0 420 172"', html)
        self.assertIn("x-axis Tap Index, y-axis Power in dB", html)
        self.assertIn("const left = 68;", source)
        self.assertNotIn("const left = 36;", source)
        self.assertIn('yAxisTitle.textContent = "Power (dB)";', source)
        self.assertIn('xAxisTitle.textContent = "Tap Index";', source)
        self.assertIn("const yTicks = [", source)
        self.assertIn('desc.textContent = "X-axis shows Tap Index. Y-axis shows tap power in dB.', source)
        self.assertIn("tapGrid", css)

    def test_mobility_mode_controls_and_api_are_wired(self) -> None:
        api_source = read_static_js("api.js")
        app_source = read_static_js("app.js")
        state_source = read_static_js("app_state.js")
        source = read_static_js("solver_controls.js")
        css_source = read_static_css("app.css")
        html = (PROJECT_ROOT / "backend" / "static" / "index.html").read_text(encoding="utf-8")

        self.assertIn('id="tabMobility"', html)
        self.assertIn('id="btnRunMobility"', html)
        self.assertIn('id="mobilityWaypointList"', html)
        self.assertIn('id="mobilityMaxSteps" type="number" step="1" min="2" max="500" value="50"', html)
        self.assertIn('id="mobilitySeriesChart"', html)
        self.assertIn('requestJson("/api/mobility/jobs"', api_source)
        self.assertIn("getMobilityJob", api_source)
        self.assertIn("getMobilityResult", api_source)
        self.assertIn("state.mode = \"mobility\";", app_source)
        self.assertIn("state.link.advanced.computeTaps = true;", app_source)
        self.assertIn("createMobilityJob", app_source)
        self.assertIn("mobility:", state_source)
        self.assertIn("points: [],", state_source)
        self.assertIn("selectedWaypointIndex: -1", state_source)
        self.assertNotIn("points: [\n        [90.0, 52.0, 1.5]", state_source)
        self.assertIn('empty.textContent = "No Rx waypoints yet";', source)
        self.assertIn('item.classList.toggle("active", index === state.mobility.selectedWaypointIndex);', source)
        self.assertIn("state.mobility.selectedWaypointIndex = index;", source)
        self.assertIn("function deleteMobilityWaypoint(index = state.mobility.selectedWaypointIndex)", source)
        self.assertNotIn("remove.disabled", source)
        self.assertNotIn("points.length <= 2", source)
        self.assertIn("state.mobility.trajectory.points = [];", source)
        self.assertNotIn("[x + 15, y + 8, z]", source)
        self.assertIn(".waypointItem.active", css_source)
        self.assertIn(".waypointEmpty", css_source)
        self.assertIn('event.key === "Enter"', app_source)
        self.assertIn("solverControls.addCurrentRxWaypoint();", app_source)
        self.assertIn('event.key === "Delete" && state.mobility.selectedWaypointIndex >= 0', app_source)
        self.assertIn("solverControls.deleteMobilityWaypoint(state.mobility.selectedWaypointIndex);", app_source)
        self.assertIn("isEditableKeyboardTarget(event.target)", app_source)
        self.assertIn("rx_trajectory: {", source)
        self.assertIn("points: state.mobility.trajectory.points", source)
        self.assertIn("max_steps: state.mobility.trajectory.maxSteps", source)
        self.assertIn("${estimate.steps} / ${estimate.maxSteps} steps", source)
        self.assertNotIn("estimate.steps > 50", source)
        self.assertIn("solver: linkSolverConfig()", source)
        self.assertIn("channel: linkChannelConfig()", source)
        self.assertIn("getViewer().renderPaths(sample?.paths || [], -1);", source)

    def test_mobility_uses_shared_result_dock_and_viewer_preview(self) -> None:
        source = read_static_js("solver_controls.js")
        viewer_source = read_static_js("viewer.js")
        scene_source = read_static_js("scene_render_state.js")
        html = (PROJECT_ROOT / "backend" / "static" / "index.html").read_text(encoding="utf-8")

        self.assertIn('id="mobilityResult"', html)
        self.assertIn('id="mobilityTimelineSection"', html)
        self.assertIn('ui.resultDockTitle.textContent = "Mobility Results";', source)
        self.assertIn("function renderMobilityResult()", source)
        self.assertIn("function renderMobilitySeriesChart(result)", source)
        self.assertIn("renderPathDetails(paths, state.mobility.selectedPath);", source)
        self.assertIn("renderMobilityResult();", scene_source)
        self.assertIn("renderMobilityTrajectory(points = [], samples = [], selectedIndex = -1)", viewer_source)
        self.assertIn("if (!Array.isArray(points) || points.length < 1)", viewer_source)
        self.assertIn("if (points.length >= 2)", viewer_source)
        self.assertIn("this.mobilityGroup = new THREE.Group();", viewer_source)

    def test_tx_orbit_showcase_button_is_wired(self) -> None:
        html = (PROJECT_ROOT / "backend" / "static" / "index.html").read_text(encoding="utf-8")
        app_source = read_static_js("app.js")
        state_source = read_static_js("app_state.js")
        dom_source = read_static_js("dom_refs.js")
        scene_source = read_static_js("scene_render_state.js")
        viewer_source = read_static_js("viewer.js")

        action_bar_index = html.index('id="deviceActionBar"')
        orbit_index = html.index('id="btnOrbitTx"')
        solve_index = html.index('id="btnSolveLink"')

        self.assertLess(action_bar_index, orbit_index)
        self.assertLess(orbit_index, solve_index)
        self.assertIn('aria-label="Orbit around transmitter"', html)
        self.assertIn('btnOrbitTx: document.getElementById("btnOrbitTx")', dom_source)
        self.assertIn("startTxOrbit() { return false; }", state_source)
        self.assertIn("stopTxOrbit() {}", state_source)
        self.assertIn("isTxOrbiting() { return false; }", state_source)
        self.assertIn("startTxOrbit(center)", viewer_source)
        self.assertIn("stopTxOrbit()", viewer_source)
        self.assertIn("isTxOrbiting()", viewer_source)
        self.assertIn('window.dispatchEvent(new CustomEvent("hku-tx-orbit-change"', viewer_source)
        self.assertIn("return state.mode === \"radiomap\" ? state.radiomap.txVisual : state.link.txVisual;", app_source)
        self.assertIn("ui.btnOrbitTx.addEventListener(\"click\", toggleTxOrbit);", app_source)
        self.assertIn("window.addEventListener(\"hku-tx-orbit-change\"", app_source)
        self.assertIn("stopTxOrbit();\n    state.mode = \"link\";", app_source)
        self.assertIn("stopTxOrbit();\n    state.mode = \"mobility\";", app_source)
        self.assertIn("stopTxOrbit();\n    state.mode = \"radiomap\";", app_source)
        self.assertIn("ui.btnResetView.addEventListener(\"click\", () => {\n    stopTxOrbit();", app_source)
        self.assertIn("ui.btnOrbitTx.classList.toggle(\"active\", orbitingTx);", scene_source)
        self.assertIn('ui.btnOrbitTx.querySelector(".deviceActionText").textContent = orbitingTx ? "Stop" : "Orbit";', scene_source)


if __name__ == "__main__":
    unittest.main()
