from __future__ import annotations

from pathlib import Path
import unittest


PROJECT_ROOT = Path(__file__).resolve().parents[1]


def read_static_js(name: str) -> str:
    return (PROJECT_ROOT / "backend" / "static" / "js" / name).read_text(encoding="utf-8")


def read_static_css(name: str) -> str:
    return (PROJECT_ROOT / "backend" / "static" / "css" / name).read_text(encoding="utf-8")


class FrontendRegressionTests(unittest.TestCase):
    def test_entry_search_focus_does_not_reset_selection_badge(self) -> None:
        source = read_static_js("entry_map.js")

        self.assertNotIn("updateEntryMapBadge(tileId)", source)
        self.assertIn("syncEntryOverviewUi();", source)
        self.assertIn("Click the tile on the map to select it.", source)
        self.assertIn("Click the tile on the map to download it.", source)

    def test_loaded_tile_status_requires_all_tile_bundles(self) -> None:
        source = read_static_js("viewer.js")

        self.assertIn("this.tileBundleCounts = new Map();", source)
        self.assertIn("this.tileExpectedBundleCounts = new Map();", source)
        self.assertIn("loadedCount === expectedCount", source)
        self.assertNotIn("loadedTileIds.add(bundle.tile)", source)

    def test_city_model_uses_category_palette_for_natural_materials(self) -> None:
        source = read_static_js("viewer.js")
        expected_category_colors = {
            "BUILDING": "#d8d2c4",
            "INFRASTRUCTURE": "#50565c",
            "INFRASTRUCTURE_TB": "#50565c",
            "GENERIC": "#8c8981",
            "TERRAIN_TB": "#8c8981",
            "VEGETATION_TB": "#557b5c",
            "WATERBODY": "#245766",
        }

        self.assertIn("const CATEGORY_MATERIAL_STYLES = {", source)
        for category, color in expected_category_colors.items():
            self.assertIn(f"{category}: {{", source)
            self.assertIn(f'color: "{color}"', source)
        self.assertIn("CATEGORY_MATERIAL_STYLES[bundle.category]", source)
        self.assertIn("const MATERIAL_FALLBACK_COLORS = {", source)
        self.assertIn("function colorForBundle(bundle)", source)
        self.assertIn("hashString(bundle.bundle_id", source)
        self.assertIn("lightnessVariation", source)
        self.assertIn("saturationVariation", source)
        self.assertIn('transparent: true', source)
        self.assertIn('opacity: 0.84', source)
        self.assertIn('Boolean(style.transparent) || bundle.bsdf_id === "itu_wet_ground"', source)
        self.assertIn("new THREE.HemisphereLight", source)
        self.assertIn("new THREE.DirectionalLight(0xdbe5f7, 0.42)", source)
        self.assertIn("toneMappingExposure = 1.08", source)
        self.assertIn("roughness: style.roughness ?? 0.88", source)
        self.assertIn("metalness: style.metalness ?? 0.0", source)
        self.assertNotIn("MATERIAL_COLORS[mesh.bsdf_id]", source)

    def test_viewer_clamps_camera_and_target_above_ground(self) -> None:
        source = read_static_js("viewer.js")
        orbit_source = (PROJECT_ROOT / "backend" / "static" / "lib" / "OrbitControls.js").read_text(encoding="utf-8")

        self.assertIn("const VIEW_GROUND_Z = 0;", source)
        self.assertIn("const VIEW_CAMERA_MIN_CLEARANCE_M = 2.0;", source)
        self.assertIn("const VIEW_TARGET_MIN_Z = 0;", source)
        self.assertIn("#clampViewAboveGround({preserveOffset = false} = {})", source)
        self.assertIn("const minCameraZ = VIEW_GROUND_Z + VIEW_CAMERA_MIN_CLEARANCE_M;", source)
        self.assertIn("this.controls.target.z = VIEW_TARGET_MIN_Z;", source)
        self.assertIn("this.camera.position.z = minCameraZ;", source)
        self.assertIn("this.#clampViewAboveGround({preserveOffset: true});", source)
        self.assertGreaterEqual(source.count("this.#clampViewAboveGround();"), 6)
        self.assertNotIn("#clampViewAboveGround", orbit_source)
        self.assertNotIn("VIEW_CAMERA_MIN_CLEARANCE_M", orbit_source)

    def test_viewer_uses_tighter_depth_range_and_layer_bias(self) -> None:
        source = read_static_js("viewer.js")

        self.assertIn("const CAMERA_NEAR_MIN = 0.3;", source)
        self.assertIn("const CAMERA_NEAR_MAX = 20;", source)
        self.assertIn("const CAMERA_FAR_MIN = 2500;", source)
        self.assertIn("const CAMERA_FAR_SCENE_PADDING = 3.5;", source)
        self.assertIn("const CAMERA_FAR_EXTRA_MARGIN = 500;", source)
        self.assertNotIn("CAMERA_FAR_MULTIPLIER", source)
        self.assertIn("this.modelBounds = new THREE.Box3();", source)
        self.assertIn("this.modelBoundsDirty = true;", source)
        self.assertIn("#currentModelBounds()", source)
        self.assertIn("modelBounds.getBoundingSphere(new THREE.Sphere())", source)
        self.assertIn("this.#markModelBoundsDirty();", source)
        self.assertIn("const targetNear = THREE.MathUtils.clamp(orbitDistance / 1000", source)
        self.assertIn("polygonOffsetFactor: 8", source)
        self.assertGreaterEqual(source.count("polygonOffsetFactor: -2"), 4)
        self.assertGreaterEqual(source.count("polygonOffsetFactor: -1"), 3)

    def test_viewer_can_render_terrain_as_background_depth_layer(self) -> None:
        source = read_static_js("viewer.js")

        self.assertIn("TERRAIN_TB: {\n    renderOrder: 0,\n    polygonOffsetFactor: 8,\n    polygonOffsetUnits: 8,\n    depthWrite: false,\n    depthTest: true,", source)
        self.assertIn("const layer = displayLayerForBundle(bundle);", source)
        self.assertIn("depthWrite: layer.depthWrite", source)
        self.assertIn("depthTest: layer.depthTest ?? true", source)
        self.assertNotIn("depthWrite: transparent ? layer.depthWrite : true", source)
        self.assertNotIn("readViewerRenderOptions", source)
        self.assertNotIn("terrainDepthWrite", source)
        self.assertNotIn("terrainDepthTest", source)
        self.assertNotIn("terrainOffsetFactor", source)
        self.assertNotIn("logarithmicDepthBuffer", source)

    def test_bundle_progress_totals_are_updated_from_runtime_headers(self) -> None:
        source = read_static_js("viewer.js")

        self.assertIn("const bundleTransferSizeById = new Map();", source)
        self.assertIn("const unresolvedBundleIds = new Set();", source)
        self.assertIn("const updateBundleSizeHints = (bundle, event = {}, fallbackLoadedBytes = null) => {", source)
        self.assertIn("positiveSizeBytes(event.totalBytes) || positiveSizeBytes(fallbackLoadedBytes)", source)
        self.assertIn("totalBytes: totalTransferBytes(),", source)
        self.assertIn("hasUnknownBytes: unresolvedBundleIds.size > 0", source)
        self.assertNotIn("const knownTotalBytes", source)

    def test_loading_progress_message_avoids_unknown_size_copy(self) -> None:
        source = read_static_js("scene_render_state.js")

        self.assertIn("function resolvingSizeSummary(event)", source)
        self.assertIn('" · resolving sizes"', source)
        self.assertIn("`${formatBytes(event.downloadedBytes)} downloaded${resolvingSizeSummary(event)}`", source)
        self.assertNotIn(" / unknown", source)
        self.assertNotIn("+ unknown", source)

    def test_tile_downloads_are_globally_gated_during_active_download(self) -> None:
        source = read_static_js("entry_map.js")

        self.assertIn("function selectEntryMapTile(tileId)", source)
        self.assertIn("async function downloadEntryMapTile(tileId)", source)
        self.assertGreaterEqual(source.count("state.entry.downloadingTileIds.size > 0"), 2)
        self.assertIn(
            'setEntrySearchHint("Finish or cancel the current tile download before starting another.", true);',
            source,
        )

    def test_entry_map_opens_for_empty_manifest_to_download_first_tile(self) -> None:
        source = read_static_js("entry_map.js")
        app_source = read_static_js("app.js")

        self.assertNotIn("if (!availableTileIds.length) {\n    return null;\n  }", source)
        self.assertIn("primaryRegion: regions[0] || null", source)
        self.assertIn("Click the tile on the map to download it.", source)
        self.assertIn("if (state.entry.overview) {\n    entryMapController.showEntryScreen();", app_source)

    def test_entry_map_uses_open3dhk_coverage_for_clickable_download_tiles(self) -> None:
        source = read_static_js("entry_map.js")
        api_source = read_static_js("api.js")
        app_source = read_static_js("app.js")
        html = (PROJECT_ROOT / "backend" / "static" / "index.html").read_text(encoding="utf-8")

        self.assertIn('requestJson("/assets/open3dhk_tile_coverage.json")', api_source)
        self.assertIn("state.entry.coverage = await getOpen3dHkTileCoverage();", app_source)
        self.assertIn("buildEntryOverview(state.manifest, state.entry.coverage)", app_source)
        self.assertIn("const coverageById = new Map();", source)
        self.assertIn("...overview.coverageById.keys()", source)
        self.assertIn("...overview.tileById.keys()", source)
        self.assertNotIn("allEntryTileIds()", source)
        self.assertNotIn("createEntryGridCanvasLayer", source)
        self.assertNotIn("entryGridPane", source)
        self.assertIn("Open3DHK has no downloadable tile at that point.", source)
        self.assertIn("outside the Open3DHK downloadable coverage", source)
        self.assertIn("Downloadable from Open3DHK", source)
        self.assertIn("Available", html)
        self.assertIn("Downloadable", html)

    def test_rt_capabilities_are_loaded_for_antenna_arrays(self) -> None:
        api_source = read_static_js("api.js")
        app_source = read_static_js("app.js")
        state_source = read_static_js("app_state.js")

        self.assertIn('requestJson("/api/rt/capabilities")', api_source)
        self.assertIn("state.rtCapabilities = await getRtCapabilities();", app_source)
        self.assertIn("solverControls.applyRtCapabilities(state.rtCapabilities);", app_source)
        self.assertIn("txArray: createDefaultAntennaArray()", state_source)
        self.assertIn("rxArray: createDefaultAntennaArray()", state_source)

    def test_rt_scene_selection_is_synced_after_tile_load(self) -> None:
        api_source = read_static_js("api.js")
        app_source = read_static_js("app.js")
        scene_source = read_static_js("scene_render_state.js")

        self.assertIn('requestJson("/api/rt/scene-selection")', api_source)
        self.assertIn('requestJson("/api/rt/scene-selection", {', api_source)
        self.assertIn("getRtSceneSelection,", app_source)
        self.assertIn("setRtSceneSelection,", app_source)
        self.assertIn("async function waitForRtSceneSelection(generation, tileIds)", scene_source)
        self.assertIn("async function syncRtSceneSelection(selectedTileIds)", scene_source)
        self.assertIn('message: "Load scene..."', scene_source)
        self.assertIn("const status = await api.setRtSceneSelection(tileIds);", scene_source)
        self.assertIn("return waitForRtSceneSelection(status.generation, tileIds);", scene_source)
        self.assertIn("await syncRtSceneSelection(selectedTiles);", scene_source)
        self.assertIn("state.tileLoadBusy = true;", scene_source)
        self.assertIn("if (state.tileLoadBusy) {\n    return;\n  }\n  const selectedTileIds", scene_source)
        self.assertIn("solver().invalidateMobilityResult({clearOverlay: false, clearPaths: false});", scene_source)
        self.assertIn("rtSceneReadyForSelection(status, tileIds)", scene_source)

    def test_scene_mode_selector_replaces_low_value_stats(self) -> None:
        html = (PROJECT_ROOT / "backend" / "static" / "index.html").read_text(encoding="utf-8")
        css_source = read_static_css("app.css")
        app_source = read_static_js("app.js")
        dom_source = read_static_js("dom_refs.js")
        scene_source = read_static_js("scene_render_state.js")

        self.assertNotIn('id="stSceneMeshes"', html)
        self.assertNotIn('id="stLoadedMeshes"', html)
        self.assertNotIn('id="stLoadedTiles"', html)
        self.assertNotIn('id="stMode"', html)
        self.assertIn('<details class="paramGroup modeSelector" id="modeSelector">', html)
        self.assertIn('id="modeSelectButton" aria-haspopup="listbox" aria-expanded="false" aria-controls="modeMenu"', html)
        self.assertIn('id="modeMenu" role="listbox" aria-label="Analysis mode"', html)
        self.assertIn('id="modeSelectTitle">Mode (Link Analysis)</span>', html)
        self.assertNotIn('id="modeSelectDescription"', html)
        self.assertNotIn("modeSelectEyebrow", html)
        self.assertNotIn("modeMenuDescription", html)
        self.assertIn('id="tabLink" type="button" role="option" aria-selected="true"', html)
        self.assertIn('id="tabMobility" type="button" role="option" aria-selected="false"', html)
        self.assertIn('id="tabRadiomap" type="button" role="option" aria-selected="false"', html)
        self.assertIn('id="tabDeepMimo" type="button" role="option" aria-selected="false"', html)
        self.assertIn('<span class="modeMenuTitle">Link Analysis</span>', html)
        self.assertIn('<span class="modeMenuTitle">Mobility Analysis</span>', html)
        self.assertIn(".modeSelector", css_source)
        self.assertIn(".modeSelector{margin:2px 0 8px}", css_source)
        self.assertIn(".modeSelectButton{box-sizing:border-box;width:100%}", css_source)
        self.assertIn(".modeMenuDot", css_source)
        self.assertIn(".modeMenuItem.active", css_source)
        self.assertIn('modeSelector: document.getElementById("modeSelector")', dom_source)
        self.assertIn('modeSelectButton: document.getElementById("modeSelectButton")', dom_source)
        self.assertIn('modeMenu: document.getElementById("modeMenu")', dom_source)
        self.assertNotIn("modeSelectDescription", dom_source)
        self.assertNotIn("stSceneMeshes", dom_source)
        self.assertNotIn("syncSceneStats", scene_source)
        self.assertIn('ui.modeSelectTitle.textContent = `Mode (${modeMeta.title})`;', scene_source)
        self.assertNotIn("modeMeta.description", scene_source)
        self.assertIn('ui.modeSelector.addEventListener("toggle"', app_source)
        self.assertIn("ui.modeSelector.open = open;", app_source)
        self.assertIn('event.key === "Escape"', app_source)

    def test_research_parameters_are_collapsible_without_outer_card(self) -> None:
        html = (PROJECT_ROOT / "backend" / "static" / "index.html").read_text(encoding="utf-8")
        css_source = read_static_css("app.css")

        self.assertNotIn("Research Parameters", html)
        self.assertNotIn("paramGroupTitle", html)
        self.assertIn('<details class="paramGroup" open>', html)
        self.assertIn('<summary class="paramGroupSummary">Physical Layer</summary>', html)
        self.assertIn('<summary class="paramGroupSummary">Antenna Arrays</summary>', html)
        self.assertIn('<summary class="paramGroupSummary">Propagation</summary>', html)
        self.assertIn('<summary class="paramGroupSummary">Solver Budget</summary>', html)
        self.assertIn('<details class="paramGroup linkOnlyParam">', html)
        self.assertIn('<details class="paramGroup radiomapOnlyParam hidden">', html)
        self.assertIn('<details class="paramGroup deepmimoOnlyParam hidden">', html)
        self.assertIn('id="cfgFrequency"', html)
        self.assertIn('id="txArrayPattern"', html)
        self.assertIn('id="linkMaxNumPaths"', html)
        self.assertNotIn("Compute CIR / Taps", html)
        self.assertIn("Compute Channel Impulse Response (CIR)", html)
        self.assertIn('aria-label="Compute CIR details"', html)
        self.assertIn("Requests compact CIR summaries after path solving.", html)
        self.assertIn(".solverCfg{margin-top:10px;padding:0;border:0;border-radius:0;background:transparent}", css_source)
        self.assertIn(".paramGroupSummary::after", css_source)
        self.assertIn(".paramGroup[open] > .paramGroupBody", css_source)
        self.assertIn('href="/css/app.css?v=20260519-deepmimo-datasets"', html)
        self.assertIn("#uiBody{min-height:0;overflow-y:auto;overflow-x:hidden;padding-right:12px;margin-right:-12px;scrollbar-gutter:stable;", css_source)
        self.assertIn("#uiBody::-webkit-scrollbar{width:10px}", css_source)
        self.assertIn("background-clip:content-box", css_source)
        self.assertIn('src="/js/app.js?v=20260519-mode-isolation"', html)

    def test_antenna_array_payloads_are_sent_to_solvers(self) -> None:
        source = read_static_js("solver_controls.js")
        html = (PROJECT_ROOT / "backend" / "static" / "index.html").read_text(encoding="utf-8")

        self.assertIn("solverConfig.tx_array = antennaArrayPayload(state.antenna.txArray)", source)
        self.assertIn("rx_array: antennaArrayPayload(state.antenna.rxArray)", source)
        self.assertIn("...commonSolverConfig(),\n      samples_per_tx", source)
        self.assertIn("samples_per_tx: state.radiomap.solver.samplesPerTx", source)
        self.assertIn('id="txArrayPattern"', html)
        self.assertIn('id="rxArrayPattern"', html)
        self.assertIn('class="paramField linkOnlyParam deepmimoAntennaParam" for="rxArrayPattern"', html)

    def test_radiomap_ui_parameters_are_wired(self) -> None:
        source = read_static_js("solver_controls.js")
        viewer_source = read_static_js("viewer.js")
        colormap_source = read_static_js("colormaps.js")
        html = (PROJECT_ROOT / "backend" / "static" / "index.html").read_text(encoding="utf-8")
        state_source = read_static_js("app_state.js")
        dom_source = read_static_js("dom_refs.js")

        self.assertIn('id="rmSamplesPerTx"', html)
        self.assertIn('id="rmCellSize"', html)
        self.assertIn('id="rmColormap"', html)
        self.assertIn('id="rmColorbarSection"', html)
        self.assertIn('id="radiomapResolutionSection"', html)
        self.assertIn('id="rmMesh"', html)
        self.assertIn('id="rmArea"', html)
        self.assertIn('id="rmCellSizeSummary"', html)
        self.assertIn("Solver Mesh", html)
        self.assertIn("Resolution &amp; Budget", html)
        self.assertIn("Display Scale", html)
        self.assertIn('<option value="jet" selected>jet</option>', html)
        self.assertIn("solver: {\n      samplesPerTx: 1000000", state_source)
        self.assertIn('colormap: "jet"', state_source)
        self.assertIn('rmSamplesPerTx: document.getElementById("rmSamplesPerTx")', dom_source)
        self.assertIn('rmMesh: document.getElementById("rmMesh")', dom_source)
        self.assertIn('rmCellSizeSummary: document.getElementById("rmCellSizeSummary")', dom_source)
        self.assertIn("surface.cell_size = state.radiomap.surface.cellSize", source)
        self.assertIn("samples_per_tx: state.radiomap.solver.samplesPerTx", source)
        self.assertNotIn("samples_per_tx: 1000000", source)
        self.assertNotIn("state.livePreview.radiomap", source)
        self.assertNotIn("function scheduleRadiomapPreview", source)
        self.assertNotIn("function runRadiomapLiveJob", source)
        self.assertIn('throw new Error(job.error || job.message || "Radio map job failed");', source)
        self.assertIn('state.radiomap.jobId = null;\n  state.radiomap.result = null;', source)
        self.assertIn('state.radiomap.status = "failed";\n    state.radiomap.result = null;', source)
        self.assertIn('surface.resolution_mode === "cell_size_grid"', source)
        self.assertIn('`${nx} x ${ny} cells (${formatCount(surface.grid_cell_count)})`', source)
        self.assertIn("surface.triangle_count", source)
        self.assertIn("colormapGradient(colormap)", source)
        self.assertIn('Colormap: ${colormap}', source)
        self.assertIn('Display limits: ${minDb.toFixed(0)} .. ${maxDb.toFixed(0)} dB', source)
        self.assertIn('import {colorForColormap} from "/js/colormaps.js";', viewer_source)
        self.assertIn("colorForColormap(colormap, clamp01", viewer_source)
        self.assertIn("const invalidColor", viewer_source)
        self.assertIn("Number.isFinite(value)", viewer_source)
        self.assertIn("rawValue !== null && Number.isFinite(value)", viewer_source)
        self.assertIn('"N/A"', source)
        self.assertIn('colormap: "jet"', viewer_source)
        self.assertIn('? name : "jet"', colormap_source)

    def test_radiomap_results_live_in_right_side_dock(self) -> None:
        html = (PROJECT_ROOT / "backend" / "static" / "index.html").read_text(encoding="utf-8")
        css_source = read_static_css("app.css")
        source = read_static_js("solver_controls.js")
        app_source = read_static_js("app.js")
        state_source = read_static_js("app_state.js")
        dom_source = read_static_js("dom_refs.js")
        scene_source = read_static_js("scene_render_state.js")

        dock_start = html.index('id="linkChannelSection"')
        link_panel_start = html.index('id="linkPanel"')
        radiomap_panel_start = html.index('id="radiomapPanel"')
        dock_html = html[dock_start:link_panel_start]
        left_panel_html = html[link_panel_start:]

        self.assertIn('id="radiomapResult"', dock_html)
        self.assertIn('id="btnResultDockToggle"', dock_html)
        self.assertIn('aria-expanded="true"', dock_html)
        self.assertIn('id="channelAnalysisScroll" class="channelAnalysisScroll"', dock_html)
        self.assertIn(".channelAnalysisDock{position:absolute;", css_source)
        self.assertIn("backdrop-filter:blur(14px);overflow:hidden;transition:", css_source)
        self.assertIn(".channelAnalysisScroll{box-sizing:border-box;max-height:calc(100vh - var(--analysis-dock-top) - 18px - 62px);overflow-x:hidden;overflow-y:auto;padding:0 12px 12px;scrollbar-width:thin;", css_source)
        self.assertIn(".channelAnalysisDock.collapsed .channelAnalysisScroll{max-height:0;padding-top:0;padding-bottom:0;opacity:0;overflow:hidden;pointer-events:none}", css_source)
        self.assertIn(".channelAnalysisDock.collapsed .channelAnalysisChevron{transform:rotate(-90deg)}", css_source)
        self.assertIn(".channelAnalysisScroll::-webkit-scrollbar{width:6px}", css_source)
        self.assertIn(".channelAnalysisScroll::-webkit-scrollbar-thumb:hover", css_source)
        self.assertNotIn(".channelAnalysisDock::-webkit-scrollbar", css_source)
        self.assertIn("resultDock: {\n    expanded: true,", state_source)
        self.assertIn('btnResultDockToggle: document.getElementById("btnResultDockToggle")', dom_source)
        self.assertIn('channelAnalysisScroll: document.getElementById("channelAnalysisScroll")', dom_source)
        self.assertIn('ui.btnResultDockToggle.addEventListener("click", () => {', app_source)
        self.assertIn("state.resultDock.expanded = !state.resultDock.expanded;", app_source)
        self.assertIn("function syncResultDockUi()", scene_source)
        self.assertIn('ui.linkChannelSection.classList.toggle("collapsed", !expanded);', scene_source)
        self.assertIn("ui.channelAnalysisScroll.inert = !expanded;", scene_source)
        self.assertIn("Radio Map Results", source)
        self.assertIn("Path gain / Terrain grid", source)
        self.assertIn("Path gain (dB)", html)
        self.assertIn("Grid", html)
        self.assertIn("Solver Mesh", html)
        self.assertIn("Area", html)
        self.assertIn("Cell Size", html)
        self.assertIn("Samples / Tx", html)
        self.assertIn("Result Range", html)
        self.assertIn("Display Scale", html)
        self.assertNotIn('id="radiomapResult"', left_panel_html[left_panel_html.index('id="radiomapPanel"'):])
        self.assertIn('ui.radiomapResult.style.display = "none";', source)
        self.assertIn('ui.linkChannelSection.classList.remove("hidden");', source)
        self.assertIn('ui.resultDockTitle.textContent = "Radio Map Results";', source)
        self.assertIn('syncModeUi();\n  syncControlSidebarUi();\n  syncViewerMarkers();', scene_source)
        self.assertIn('syncPerformanceUi();\n  syncResultDockUi();', scene_source)
        self.assertIn('button.removeAttribute("aria-busy");\n    sceneRenderState.renderAll();', app_source)

    def test_live_preview_controls_and_schedulers_are_wired(self) -> None:
        html = (PROJECT_ROOT / "backend" / "static" / "index.html").read_text(encoding="utf-8")
        app_source = read_static_js("app.js")
        api_source = read_static_js("api.js")
        dom_source = read_static_js("dom_refs.js")
        scene_source = read_static_js("scene_render_state.js")
        solver_source = read_static_js("solver_controls.js")
        state_source = read_static_js("app_state.js")
        viewer_source = read_static_js("viewer.js")
        css_source = read_static_css("app.css")

        self.assertIn('id="livePreviewStatus"', html)
        self.assertIn('id="livePreviewEnabled" type="checkbox"', html)
        self.assertIn('id="livePreviewLinkSamples"', html)
        self.assertIn('<span class="paramLabel">Preview Samples / Source', html)
        self.assertIn('id="livePreviewPathsDelay"', html)
        self.assertNotIn('id="livePreviewRmSamples"', html)
        self.assertNotIn('id="livePreviewRmDelay"', html)
        self.assertNotIn('id="livePreviewRmCellSize"', html)
        self.assertIn('class="devicePrecisionPanel deviceCompactBar hidden"', html)
        self.assertNotIn("devicePrecisionKicker", html)
        self.assertIn('id="devicePrecisionTitle" class="devicePrecisionTitle">Tx</div>', html)
        self.assertIn("Pick a surface point or fine-tune below.", html)
        self.assertIn('id="linkSurfaceClearance"', html)
        self.assertIn('value="1.5"', html)
        self.assertIn(">Clearance\n", html)
        self.assertIn("Distance from the picked surface for the active mode device.", html)
        self.assertIn(".deviceDock{position:absolute;left:50%;bottom:16px;z-index:17;width:auto;max-width:min(600px, calc(100vw - 420px));min-width:0", css_source)
        self.assertIn(".livePreviewParam .paramCheckGrid + .paramGrid{margin-top:12px}", css_source)
        self.assertIn(".devicePrecisionPanel{width:auto;max-width:100%;", css_source)
        self.assertIn(".deviceCompactBar{display:flex;align-items:center;gap:6px;min-height:44px}", css_source)
        self.assertIn(".devicePrecisionStatus{position:absolute;width:1px;height:1px;overflow:hidden;clip-path:inset(50%);white-space:nowrap}", css_source)
        self.assertIn(".deviceCoordPanels{min-width:0;display:flex;align-items:center;gap:6px;flex:0 1 auto}", css_source)
        self.assertIn(".deviceCoordPanel{min-width:0;flex:0 0 auto}", css_source)
        self.assertIn(".deviceCoordGrid{display:grid;grid-template-columns:repeat(3,104px);gap:5px}", css_source)
        self.assertIn("text-align:left;font-variant-numeric:tabular-nums", css_source)
        self.assertIn(".deviceCoordGrid .unitInput input[type=\"number\"],.deviceClearanceField .unitInput input[type=\"number\"]{padding-right:24px}", css_source)
        self.assertIn(".deviceCoordGrid .unitSuffix,.deviceClearanceField .unitSuffix{right:6px;font-size:10px}", css_source)
        self.assertIn(".deviceClearanceField{display:flex;align-items:center;gap:5px;flex:0 0 166px", css_source)
        self.assertIn(".deviceCompactBar{flex-wrap:wrap;gap:6px}", css_source)
        self.assertIn("livePreview: {\n    enabled: false", state_source)
        self.assertIn("previewSamplesPerSrc: 1000", state_source)
        self.assertIn("surfaceClearanceM: 1.5", state_source)
        self.assertGreaterEqual(state_source.count("surfaceClearanceM: 1.5"), 2)
        self.assertNotIn("mapDelayS: 3.0", state_source)
        self.assertNotIn("previewSamplesPerTx", state_source)
        self.assertIn('livePreviewEnabled: document.getElementById("livePreviewEnabled")', dom_source)
        self.assertIn('linkSurfaceClearance: document.getElementById("linkSurfaceClearance")', dom_source)
        self.assertIn('livePreviewParams: [...document.querySelectorAll(".livePreviewParam")]', dom_source)
        self.assertIn('node.classList.toggle("hidden", !isLink);', scene_source)
        self.assertIn('ui.linkSurfaceClearanceField.classList.toggle("hidden"', scene_source)
        self.assertIn('nextActiveTarget === "rm-tx"', scene_source)
        self.assertIn('nextActiveTarget === "deepmimo-roi"\n      ? "ROI"', scene_source)
        self.assertIn('nextActiveTarget === "rm-tx"\n      ? "RM Tx"', scene_source)
        self.assertIn('export function solveLink(payload, options = {})', api_source)
        self.assertIn("signal: options.signal", api_source)

        self.assertIn("function linkSolvePayload({preview = false} = {})", solver_source)
        self.assertIn("solver.samples_per_src = Math.max(1, Math.floor(Number(state.livePreview.link.previewSamplesPerSrc)));", solver_source)
        self.assertIn("solver.max_num_paths_per_src = Math.min(Number(solver.max_num_paths_per_src), 10000);", solver_source)
        self.assertIn("channel.compute_taps = false;", solver_source)
        self.assertIn("new AbortController()", solver_source)
        self.assertIn("token !== live.generation", solver_source)
        self.assertIn("function radiomapJobPayload()", solver_source)
        self.assertIn("density_level: state.radiomap.surface.densityLevel", solver_source)
        self.assertNotIn("Math.max(Number(state.radiomap.surface.cellSize), previewCellSize)", solver_source)
        self.assertNotIn("live.inFlight = true;", solver_source)
        self.assertNotIn("live.pendingPreview = true;", solver_source)
        self.assertNotIn("live.pendingFinal = true;", solver_source)
        self.assertIn("live.previewController?.abort();\n    live.finalController?.abort();", solver_source)
        self.assertIn('setLivePreviewStatus("link", preview ? "Previewing" : "Finalizing");', solver_source)
        self.assertNotIn('setLivePreviewStatus("radiomap"', solver_source)
        self.assertIn("handleLivePreviewDeviceUpdate(target, phase = \"change\")", solver_source)
        self.assertIn("function linkPickPosition(pick)", solver_source)
        self.assertIn("function radiomapTxPickPosition(pick)", solver_source)
        self.assertIn("pick.surfacePosition", solver_source)
        self.assertIn("pick.surfaceNormal", solver_source)
        self.assertIn("state.link.surfaceClearanceM", solver_source)
        self.assertIn("state.radiomap.surfaceClearanceM", solver_source)
        self.assertIn("const position = radiomapTxPickPosition(pick);", solver_source)
        self.assertIn("setLogicalAndVisual(state.radiomap.tx, state.radiomap.txVisual, position);", solver_source)
        self.assertIn("surfacePosition: [hit.point.x, hit.point.y, hit.point.z]", viewer_source)
        self.assertIn("surfaceNormal: surfaceNormal ?", viewer_source)

        self.assertIn("solverControls.cancelLivePreview();\n  state.pickTarget = null;", app_source)
        self.assertIn('view.addEventListener("pointerdown", handlePickPointerDown, {capture: true});', app_source)
        self.assertIn("event.currentTarget.setPointerCapture(event.pointerId);", app_source)
        self.assertIn('document.getElementById("view").releasePointerCapture(event.pointerId);', app_source)
        self.assertIn('solverControls.handleLivePreviewDeviceUpdate(target, livePhase);', app_source)
        self.assertIn('solverControls.handleLivePreviewDeviceUpdate(target, "change");', app_source)
        self.assertIn('[inputs.linkRxX, "link-rx"]', app_source)
        self.assertNotIn('solverControls.handleLivePreviewDeviceUpdate("rm-tx", "change");', app_source)
        self.assertIn('inputs.linkSurfaceClearance.addEventListener("change"', app_source)
        self.assertIn("solverControls.readSurfaceClearanceInput();", app_source)

    def test_path_details_show_array_pair_aggregation(self) -> None:
        source = read_static_js("solver_controls.js")

        self.assertIn('addField("Array Pairs", String(path.array_pair_count ?? 1));', source)
        self.assertIn('addField("Strongest Pair", formatFixed(path.strongest_pair_power_db, 2, " dB"));', source)

    def test_link_results_live_in_right_side_dock(self) -> None:
        html = (PROJECT_ROOT / "backend" / "static" / "index.html").read_text(encoding="utf-8")
        source = read_static_js("solver_controls.js")

        dock_start = html.index('id="linkChannelSection"')
        link_panel_start = html.index('id="linkPanel"')
        radiomap_panel_start = html.index('id="radiomapPanel"')
        dock_html = html[dock_start:link_panel_start]
        link_panel_html = html[link_panel_start:radiomap_panel_start]
        tap_index = dock_html.index('id="linkTapAnalysisSection"')
        selection_index = dock_html.index('id="pathSelectionSection"')
        buttons_index = dock_html.index('id="pathButtons"')

        self.assertIn("Link Results", dock_html)
        self.assertIn('id="linkResult"', dock_html)
        self.assertIn('id="pathSelectionSection"', dock_html)
        self.assertIn('id="pathSelectionCount"', dock_html)
        self.assertIn('id="pathButtons"', dock_html)
        self.assertIn('id="pathDetailSection"', dock_html)
        self.assertIn('id="linkTapAnalysisSection"', dock_html)
        self.assertLess(tap_index, selection_index)
        self.assertLess(selection_index, buttons_index)
        self.assertNotIn('id="linkResult"', link_panel_html)
        self.assertNotIn('id="pathSelectionSection"', link_panel_html)
        self.assertNotIn('id="pathButtons"', link_panel_html)
        self.assertNotIn('id="pathDetailSection"', link_panel_html)
        self.assertNotIn("Channel Result", html)
        self.assertIn("function renderPathSelection(paths, selectedIndex, onSelect)", source)
        self.assertIn('ui.pathSelectionSection.classList.add("hidden");', source)
        self.assertIn('ui.pathSelectionSection.classList.remove("hidden");', source)
        self.assertIn("getViewer().renderPaths(result.paths, index);", source)
        self.assertIn("getViewer().renderPaths(paths, index);", source)

    def test_tap_analysis_no_longer_controls_whole_link_result_dock(self) -> None:
        source = read_static_js("solver_controls.js")
        render_channel = source[
            source.index("function renderLinkChannel"):
            source.index("function renderLinkResult")
        ]

        self.assertIn('ui.linkTapAnalysisSection.classList.add("hidden");', render_channel)
        self.assertIn('ui.linkTapAnalysisSection.classList.remove("hidden");', render_channel)
        self.assertNotIn("ui.linkChannelSection.classList.add", render_channel)
        self.assertNotIn("ui.linkChannelSection.classList.remove", render_channel)

    def test_tap_chart_axes_are_labeled_and_not_clipped(self) -> None:
        source = read_static_js("solver_controls.js")
        html = (PROJECT_ROOT / "backend" / "static" / "index.html").read_text(encoding="utf-8")
        css = (PROJECT_ROOT / "backend" / "static" / "css" / "app.css").read_text(encoding="utf-8")

        self.assertIn('viewBox="0 0 420 172"', html)
        self.assertIn("x-axis Tap Index, y-axis Power in dB", html)
        self.assertIn("const left = 68;", source)
        self.assertNotIn("const left = 36;", source)
        self.assertIn('yAxisTitle.textContent = "Power (dB)";', source)
        self.assertIn('xAxisTitle.textContent = "Tap Index";', source)
        self.assertIn("const yTicks = [", source)
        self.assertIn('desc.textContent = "X-axis shows Tap Index. Y-axis shows tap power in dB.', source)
        self.assertIn("tapGrid", css)

    def test_mobility_mode_controls_and_api_are_wired(self) -> None:
        api_source = read_static_js("api.js")
        app_source = read_static_js("app.js")
        state_source = read_static_js("app_state.js")
        source = read_static_js("solver_controls.js")
        css_source = read_static_css("app.css")
        html = (PROJECT_ROOT / "backend" / "static" / "index.html").read_text(encoding="utf-8")

        self.assertIn('id="tabMobility"', html)
        self.assertIn('id="btnRunMobility"', html)
        self.assertIn('id="mobilityWaypointList"', html)
        self.assertIn('id="mobilityMaxSteps" type="number" step="1" min="2" max="10000" value="1000"', html)
        self.assertNotIn('id="mobilityMaxSteps" type="number" step="1" min="2" max="500"', html)
        self.assertIn('id="mobilitySeriesChart"', html)
        self.assertIn('id="mobilityTxDeviceCard"', html)
        self.assertIn('id="mobilityRxDeviceCard"', html)
        self.assertIn('id="mobilityTxX"', html)
        self.assertIn('id="mobilityRxX"', html)
        self.assertIn('id="btnPickMobilityTx"', html)
        self.assertIn('id="btnPickMobilityRx"', html)
        self.assertIn('requestJson("/api/mobility/jobs"', api_source)
        self.assertIn("getMobilityJob", api_source)
        self.assertIn("getMobilityResult", api_source)
        self.assertIn("state.mode = \"mobility\";", app_source)
        self.assertIn("state.link.advanced.computeTaps = true;", app_source)
        self.assertIn("createMobilityJob", app_source)
        self.assertIn("mobility:", state_source)
        self.assertIn("tx: [72.0, 37.0, 40.0]", state_source)
        self.assertIn("rx: [90.0, 52.0, 1.5]", state_source)
        self.assertIn("txVisual: [72.0, 37.0, 40.0]", state_source)
        self.assertIn("rxVisual: [90.0, 52.0, 1.5]", state_source)
        self.assertIn("surfaceClearanceM: 1.5", state_source)
        self.assertIn("points: [],", state_source)
        self.assertIn("selectedWaypointIndex: -1", state_source)
        self.assertNotIn("points: [\n        [90.0, 52.0, 1.5]", state_source)
        self.assertIn('empty.textContent = "No Rx waypoints yet";', source)
        self.assertIn('item.classList.toggle("active", index === state.mobility.selectedWaypointIndex);', source)
        self.assertIn("state.mobility.selectedWaypointIndex = index;", source)
        self.assertIn("function deleteMobilityWaypoint(index = state.mobility.selectedWaypointIndex)", source)
        self.assertNotIn("remove.disabled", source)
        self.assertNotIn("points.length <= 2", source)
        self.assertIn("state.mobility.trajectory.points = [];", source)
        self.assertNotIn("[x + 15, y + 8, z]", source)
        self.assertIn(".waypointItem.active", css_source)
        self.assertIn(".waypointEmpty", css_source)
        self.assertIn('event.key === "Enter"', app_source)
        self.assertIn("solverControls.addCurrentRxWaypoint();", app_source)
        self.assertIn('event.key === "Delete" && state.mobility.selectedWaypointIndex >= 0', app_source)
        self.assertIn("solverControls.deleteMobilityWaypoint(state.mobility.selectedWaypointIndex);", app_source)
        self.assertIn("isEditableKeyboardTarget(event.target)", app_source)
        self.assertIn("rx_trajectory: {", source)
        self.assertIn("tx: {position: state.mobility.tx, orientation: [0, 0, 0]}", source)
        self.assertIn("points: state.mobility.trajectory.points", source)
        self.assertIn("max_steps: state.mobility.trajectory.maxSteps", source)
        self.assertIn("const point = [...state.mobility.rx];", source)
        self.assertIn('state.pickTarget === "mobility-tx"', source)
        self.assertIn("setLogicalAndVisual(state.mobility.rx, state.mobility.rxVisual", source)
        self.assertIn("${estimate.steps} / ${estimate.maxSteps} steps", source)
        self.assertNotIn("estimate.steps > 50", source)
        self.assertNotIn("estimate.maxSteps > 500", source)
        self.assertNotIn("between 2 and 500", source)
        self.assertIn("solver: linkSolverConfig()", source)
        self.assertIn("channel: linkChannelConfig()", source)
        self.assertIn("getViewer().renderPaths(sample?.paths || [], -1);", source)
        self.assertIn('state.mobility.jobId = null;\n  state.mobility.result = null;', source)
        self.assertIn('state.mobility.status = "failed";\n    state.mobility.result = null;', source)

    def test_mobility_uses_shared_result_dock_and_viewer_preview(self) -> None:
        source = read_static_js("solver_controls.js")
        viewer_source = read_static_js("viewer.js")
        scene_source = read_static_js("scene_render_state.js")
        html = (PROJECT_ROOT / "backend" / "static" / "index.html").read_text(encoding="utf-8")

        self.assertIn('id="mobilityResult"', html)
        self.assertIn('id="mobilityTimelineSection"', html)
        self.assertIn('ui.resultDockTitle.textContent = "Mobility Results";', source)
        self.assertIn("function renderMobilityResult()", source)
        self.assertIn("function renderMobilitySeriesChart(result)", source)
        self.assertIn("renderPathDetails(paths, state.mobility.selectedPath);", source)
        self.assertIn("renderMobilityResult();", scene_source)
        self.assertIn("renderMobilityTrajectory(points = [], samples = [], selectedIndex = -1)", viewer_source)
        self.assertIn("if (!Array.isArray(points) || points.length < 1)", viewer_source)
        self.assertIn("if (points.length >= 2)", viewer_source)
        self.assertIn("this.mobilityGroup = new THREE.Group();", viewer_source)
        self.assertIn("getViewer().setTx(state.mobility.txVisual);", source)
        self.assertIn("getViewer().setRx(sample?.rx_position || state.mobility.rxVisual);", source)
        self.assertIn("if (state.mode !== \"mobility\") {\n    getViewer().clearMobility();", source)

    def test_mode_specific_device_visuals_are_isolated(self) -> None:
        app_source = read_static_js("app.js")
        scene_source = read_static_js("scene_render_state.js")
        solver_source = read_static_js("solver_controls.js")
        viewer_source = read_static_js("viewer.js")

        self.assertIn('"mobility-tx": "Mobility Tx"', app_source)
        self.assertIn('"mobility-rx": "Mobility Rx"', app_source)
        self.assertIn('openDevicePrecision("mobility-tx")', app_source)
        self.assertIn('openDevicePrecision("mobility-rx")', app_source)
        self.assertIn('activeTarget === "mobility-tx" || activeTarget === "mobility-rx"', scene_source)
        self.assertIn('ui.btnPickLinkTx.classList.toggle("hidden", !isLink);', scene_source)
        self.assertIn('ui.btnPickMobilityTx.classList.toggle("hidden", !isMobility);', scene_source)
        self.assertIn("syncViewerMarkers();\n  syncModeVisuals();", scene_source)

        self.assertIn("getViewer().setTx(state.radiomap.txVisual);\n    getViewer().setRx(null);", solver_source)
        self.assertIn("getViewer().setTx(state.deepmimo.txVisual);\n    getViewer().setRx(null);", solver_source)
        self.assertIn("function syncModeVisuals()", solver_source)
        self.assertIn('if (state.mode !== "radiomap") {\n    getViewer().clearRadiomap();', solver_source)
        self.assertIn('if (state.mode !== "deepmimo") {\n    getViewer().clearDeepMimoRoi();', solver_source)
        self.assertIn('if (state.mode !== "mobility") {\n    getViewer().clearMobility();', solver_source)
        self.assertIn('if (state.mode !== "link" && state.mode !== "mobility") {\n    getViewer().clearPaths();', solver_source)
        self.assertIn('if (bounds && state.mode === "deepmimo")', solver_source)
        self.assertIn('const shouldShow = state.mode === "radiomap"', solver_source)
        self.assertIn('if (state.mode !== "mobility") {\n    getViewer().clearMobility();', solver_source)
        self.assertIn("if (!Array.isArray(position)) {\n      this.stopTxOrbit();\n      this.txMarker.visible = false;", viewer_source)
        self.assertIn("if (!Array.isArray(position)) {\n      this.rxMarker.visible = false;", viewer_source)

    def test_tx_orbit_showcase_button_is_wired(self) -> None:
        html = (PROJECT_ROOT / "backend" / "static" / "index.html").read_text(encoding="utf-8")
        app_source = read_static_js("app.js")
        state_source = read_static_js("app_state.js")
        dom_source = read_static_js("dom_refs.js")
        scene_source = read_static_js("scene_render_state.js")
        viewer_source = read_static_js("viewer.js")

        action_bar_index = html.index('id="deviceActionBar"')
        orbit_index = html.index('id="btnOrbitTx"')
        solve_index = html.index('id="btnSolveLink"')

        self.assertLess(action_bar_index, orbit_index)
        self.assertLess(orbit_index, solve_index)
        self.assertIn('aria-label="Orbit around transmitter"', html)
        self.assertIn('btnOrbitTx: document.getElementById("btnOrbitTx")', dom_source)
        self.assertIn("startTxOrbit() { return false; }", state_source)
        self.assertIn("stopTxOrbit() {}", state_source)
        self.assertIn("isTxOrbiting() { return false; }", state_source)
        self.assertIn("startTxOrbit(center)", viewer_source)
        self.assertIn("stopTxOrbit()", viewer_source)
        self.assertIn("isTxOrbiting()", viewer_source)
        self.assertIn('window.dispatchEvent(new CustomEvent("hku-tx-orbit-change"', viewer_source)
        self.assertIn("if (state.mode === \"deepmimo\") {\n    return state.deepmimo.txVisual;", app_source)
        self.assertIn("if (state.mode === \"mobility\") {\n    return state.mobility.txVisual;", app_source)
        self.assertIn("ui.btnOrbitTx.addEventListener(\"click\", toggleTxOrbit);", app_source)
        self.assertIn("window.addEventListener(\"hku-tx-orbit-change\"", app_source)
        self.assertIn("stopTxOrbit();\n    state.mode = \"link\";", app_source)
        self.assertIn("stopTxOrbit();\n    state.mode = \"mobility\";", app_source)
        self.assertIn("stopTxOrbit();\n    state.mode = \"radiomap\";", app_source)
        self.assertNotIn('id="btnResetView"', html)
        self.assertNotIn('id="btnClearOverlay"', html)
        self.assertNotIn('class="actions"', html)
        self.assertNotIn("btnResetView", dom_source)
        self.assertNotIn("btnClearOverlay", dom_source)
        self.assertNotIn("btnResetView.addEventListener", app_source)
        self.assertNotIn("btnClearOverlay.addEventListener", app_source)
        self.assertIn("ui.btnOrbitTx.classList.toggle(\"active\", orbitingTx);", scene_source)
        self.assertIn('ui.btnOrbitTx.querySelector(".deviceActionText").textContent = orbitingTx ? "Stop" : "Orbit";', scene_source)

    def test_deepmimo_roi_export_controls_are_wired(self) -> None:
        html = (PROJECT_ROOT / "backend" / "static" / "index.html").read_text(encoding="utf-8")
        app_source = read_static_js("app.js")
        api_source = read_static_js("api.js")
        dom_source = read_static_js("dom_refs.js")
        state_source = read_static_js("app_state.js")
        scene_source = read_static_js("scene_render_state.js")
        solver_source = read_static_js("solver_controls.js")
        viewer_source = read_static_js("viewer.js")
        css_source = read_static_css("app.css")
        deepmimo_payload_source = solver_source.split("function deepMimoPayload()", 1)[1].split(
            "function renderDeepMimoState()",
            1,
        )[0]

        self.assertIn('id="tabDeepMimo"', html)
        self.assertIn('id="btnDeepMimoPickTx"', html)
        self.assertIn('id="btnDeepMimoPickRoi"', html)
        self.assertIn('id="btnDeepMimoClearRoi"', html)
        self.assertIn('id="deepMimoTxDeviceCard"', html)
        self.assertIn('id="deepMimoTxX"', html)
        self.assertIn('<span class="deviceActionText">Draw ROI</span>', html)
        self.assertIn('<span class="deviceActionText">Clear ROI</span>', html)
        self.assertIn('id="deepMimoRoiCenterX"', html)
        self.assertIn('id="deepMimoRoiWidth"', html)
        self.assertIn('id="deepMimoGridSpacing"', html)
        self.assertIn('id="deepMimoMaxReceivers" type="number" step="1000" min="1" max="200000" value="30000"', html)
        self.assertNotIn('id="deepMimoRoiSummary"', html)
        self.assertIn('id="deepMimoRxCandidates" type="text" value="--" readonly', html)
        self.assertNotIn('id="deepMimoSceneBuffer"', html)
        self.assertIn('<summary class="paramGroupSummary">DeepMIMO ROI</summary>', html)
        self.assertNotIn("DeepMIMO ROI Export · Selected Tiles", html)
        self.assertNotIn('id="deepMimoJobStatus"', html)
        self.assertNotIn('id="deepMimoProgress"', html)
        self.assertNotIn('id="deepMimoProgressFill"', html)
        self.assertNotIn('id="deepMimoProgressPercent"', html)
        self.assertNotIn('id="deepMimoDownloadLink"', html)
        self.assertNotIn("Download Dataset", html)
        self.assertIn('id="deepMimoDatasetTray" class="deepMimoDatasetTray hidden" aria-hidden="true"', html)
        self.assertIn('id="deepMimoDatasetToggle"', html)
        self.assertIn('id="deepMimoDatasetCount"', html)
        self.assertIn('id="deepMimoDatasetPanel"', html)
        self.assertIn('id="deepMimoDatasetList"', html)
        self.assertIn('requestJson("/api/deepmimo/jobs"', api_source)
        self.assertIn('cancelDeepMimoJob(jobId)', api_source)
        self.assertIn('`/api/deepmimo/jobs/${encodeURIComponent(jobId)}/cancel`', api_source)
        self.assertIn('`/api/deepmimo/jobs/${encodeURIComponent(jobId)}/download`', api_source)
        self.assertIn('deepMimoTxX: document.getElementById("deepMimoTxX")', dom_source)
        self.assertIn('deepMimoRoiCenterX: document.getElementById("deepMimoRoiCenterX")', dom_source)
        self.assertNotIn("deepMimoRoiSummary", dom_source)
        self.assertIn('deepMimoRxCandidates: document.getElementById("deepMimoRxCandidates")', dom_source)
        self.assertIn('deepMimoDatasetTray: document.getElementById("deepMimoDatasetTray")', dom_source)
        self.assertIn('deepMimoDatasetToggle: document.getElementById("deepMimoDatasetToggle")', dom_source)
        self.assertIn('deepMimoDatasetList: document.getElementById("deepMimoDatasetList")', dom_source)
        self.assertIn('deepmimoAntennaParams: [...document.querySelectorAll(".deepmimoAntennaParam")]', dom_source)
        self.assertNotIn("deepMimoDownloadLink", dom_source)
        self.assertNotIn("deepMimoSceneBuffer", dom_source)
        self.assertIn('deepMimoGridSpacing: document.getElementById("deepMimoGridSpacing")', dom_source)
        self.assertNotIn("deepMimoJobStatus", dom_source)
        self.assertNotIn("deepMimoProgress", dom_source)
        self.assertIn('deepMimoTxDeviceCard: document.getElementById("deepMimoTxDeviceCard")', dom_source)
        self.assertIn('btnDeepMimoPickRoi: document.getElementById("btnDeepMimoPickRoi")', dom_source)
        self.assertIn('btnDeepMimoClearRoi: document.getElementById("btnDeepMimoClearRoi")', dom_source)
        self.assertIn("deepmimo: {", state_source)
        self.assertIn("tx: [72.0, 37.0, 40.0]", state_source)
        self.assertIn("maxReceivers: 30000", state_source)
        self.assertIn("visualZ: null", state_source)
        self.assertIn("datasets: []", state_source)
        self.assertIn("datasetTrayOpen: false", state_source)
        self.assertIn('/js/app_state.js?v=20260519-mode-isolation', app_source)
        self.assertIn('/js/dom_refs.js?v=20260519-mode-isolation', app_source)
        self.assertIn('/js/solver_controls.js?v=20260519-mode-isolation', app_source)
        self.assertIn('/js/scene_render_state.js?v=20260519-mode-isolation', app_source)
        self.assertIn('ui.deepMimoDatasetToggle.addEventListener("click"', app_source)
        self.assertIn("closeDeepMimoDatasetTray();", app_source)
        self.assertIn("state.mode = \"deepmimo\";", app_source)
        self.assertIn('openDevicePrecision("deepmimo-tx")', app_source)
        self.assertIn('if (state.pickTarget === "deepmimo-roi" || state.deviceControl.activeTarget === "deepmimo-roi")', app_source)
        self.assertIn('state.deepmimo.roi.pickingStep = "a";\n      state.pickTarget = null;', app_source)
        self.assertIn('state.pickTarget = "deepmimo-roi";', app_source)
        self.assertIn("solverControls.startDeepMimoRoiDrag(position);", app_source)
        self.assertIn("solverControls.updateDeepMimoRoiDrag(position);", app_source)
        self.assertIn("solverControls.finishDeepMimoRoiDrag(position);", app_source)
        self.assertIn('if (target === "deepmimo-roi")', app_source)
        self.assertIn('const hasPrecisionTarget = nextActiveTarget === "link-tx"', scene_source)
        self.assertIn('|| nextActiveTarget === "mobility-tx"', scene_source)
        self.assertIn('|| nextActiveTarget === "mobility-rx"', scene_source)
        self.assertIn('|| nextActiveTarget === "deepmimo-tx";', scene_source)
        self.assertIn('!sceneControlsVisible || !hasPrecisionTarget', scene_source)
        self.assertIn('import("/js/viewer.js?v=20260519-mode-isolation")', scene_source)
        self.assertIn('ui.btnDeepMimoPickRoi.classList.toggle("hidden", !isDeepMimo);', scene_source)
        self.assertIn('ui.btnDeepMimoClearRoi.classList.toggle("hidden", !isDeepMimo);', scene_source)
        self.assertIn('const isDeepMimoAntennaParam = node.classList.contains("deepmimoAntennaParam");', scene_source)
        self.assertIn('node.classList.toggle("hidden", !(isLinkLike || (isDeepMimo && isDeepMimoAntennaParam)));', scene_source)
        self.assertIn("renderDeepMimoState();", scene_source)
        self.assertIn("const DEEPMIMO_FIXED_ANTENNA_ARRAY = Object.freeze({", solver_source)
        self.assertIn("numRows: 1", solver_source)
        self.assertIn("numCols: 1", solver_source)
        self.assertIn("verticalSpacing: 0.5", solver_source)
        self.assertIn("horizontalSpacing: 0.5", solver_source)
        self.assertIn('pattern: "iso"', solver_source)
        self.assertIn('polarization: "V"', solver_source)
        self.assertIn("setAntennaInputsDisabled(refs, fixedForDeepMimo);", solver_source)
        self.assertIn('if (state.mode === "deepmimo") {\n    return;\n  }', solver_source)
        self.assertIn("function readDeepMimoRoiInputs()", solver_source)
        self.assertIn("function setDeepMimoRoiFromCenter", solver_source)
        self.assertNotIn("z: Math.max(Number(cornerA[2] || 0), Number(cornerB[2] || 0))", solver_source)
        self.assertIn("state.deepmimo.roi.visualZ = visualZ;", solver_source)
        self.assertIn("state.deepmimo.roi.cornerB = [Number(position[0]), Number(position[1]), visualZ];", solver_source)
        self.assertIn("state.deepmimo.roi.visualZ = null;", solver_source)
        self.assertIn("function deepMimoPayload()", solver_source)
        self.assertIn("function deepMimoReceiverAxisCount(size, spacing)", solver_source)
        # Frontend mirrors backend receiver_grid_axis_count (inclusive floor +
        # 1, with the same 1e-9 epsilon).
        self.assertIn("Math.floor((numericSize / numericSpacing) + 1e-9) + 1", solver_source)
        self.assertIn("const nx = deepMimoReceiverAxisCount(bounds.size[0], spacing);", solver_source)
        self.assertNotIn("Math.ceil(Number(size) / spacing + 0.5)", solver_source)
        self.assertIn('ui.deepMimoRxCandidates.value = bounds && Number.isFinite(estimate)', solver_source)
        self.assertIn("tx: {position: state.deepmimo.tx, orientation: [0, 0, 0]}", solver_source)
        self.assertIn("setLogicalAndVisual(state.deepmimo.tx, state.deepmimo.txVisual", solver_source)
        self.assertNotIn("buffer_m", solver_source)
        self.assertNotIn("crop_to_roi", solver_source)
        self.assertNotIn("ui.deepMimoJobStatus", solver_source)
        self.assertIn("Load at least one selected tile before exporting DeepMIMO", solver_source)
        self.assertIn("getViewer().loadedTileIds.size", solver_source)
        self.assertIn("synthetic_array: true", solver_source)
        self.assertIn("...commonSolverConfig({includeTxArray: false}),", deepmimo_payload_source)
        self.assertNotIn("tx_array", deepmimo_payload_source)
        self.assertNotIn("rx_array", deepmimo_payload_source)
        self.assertIn("createDeepMimoJob(payload)", solver_source)
        self.assertIn('state.deepmimo.jobId = null;\n  state.deepmimo.result = null;', solver_source)
        self.assertIn('state.deepmimo.jobId = null;\n    state.deepmimo.status = "failed";', solver_source)
        self.assertNotIn("ui.deepMimoProgress", solver_source)
        self.assertIn("function renderDeepMimoDatasetTray()", solver_source)
        self.assertIn("addDeepMimoDataset(job);", solver_source)
        self.assertIn("cancelDeepMimoExport(jobId);", solver_source)
        self.assertIn('cancelLabel: "Cancel Export"', solver_source)
        self.assertIn('if (job.status === "cancelled")', solver_source)
        self.assertIn('if (job.status === "succeeded")', solver_source)
        self.assertIn('state.deepmimo.status = "succeeded";', solver_source)
        self.assertIn("state.deepmimo.datasets = [", solver_source)
        self.assertIn("deepMimoDownloadUrl(jobId)", solver_source)
        self.assertNotIn("ui.deepMimoDownloadLink", solver_source)
        self.assertIn('title: "Exporting DeepMIMO Dataset"', solver_source)
        self.assertIn("await pollDeepMimo(job.job_id);", solver_source)
        self.assertIn('if (bounds && state.mode === "deepmimo")', solver_source)
        self.assertIn("getViewer().renderDeepMimoRoi(bounds, state.deepmimo.roi.visualZ);", solver_source)
        self.assertIn("renderDeepMimoRoi(bounds, visualZ = 0)", viewer_source)
        self.assertIn("const z = Number(visualZ || 0) + 0.18;", viewer_source)
        self.assertIn("depthTest: false", viewer_source)
        self.assertIn("clearDeepMimoRoi()", viewer_source)
        self.assertIn('aria-label="DeepMIMO scenario name details"', html)
        self.assertIn("Dataset folder/name used in the DeepMIMO export.", html)
        self.assertIn('aria-label="DeepMIMO ROI center X details"', html)
        self.assertIn("ROI rectangle center X coordinate in the local scene frame.", html)
        self.assertIn('aria-label="DeepMIMO ROI width details"', html)
        self.assertIn("Rectangle span along local X.", html)
        self.assertIn('aria-label="DeepMIMO Rx spacing details"', html)
        self.assertIn("Smaller spacing creates denser datasets and higher runtime.", html)
        self.assertIn('aria-label="DeepMIMO Rx height details"', html)
        self.assertIn("Receiver height above the sampled terrain surface.", html)
        self.assertIn("The ROI footprint controls XY only.", html)
        self.assertIn('aria-label="DeepMIMO max receivers details"', html)
        self.assertIn("Safety cap for generated receiver candidates.", html)
        self.assertIn('aria-label="DeepMIMO chunk size details"', html)
        self.assertIn("Receivers traced per worker batch.", html)
        self.assertIn('aria-label="DeepMIMO samples per source details"', html)
        self.assertIn("Monte Carlo rays per transmitter for each chunk.", html)
        self.assertIn('aria-label="DeepMIMO max paths per source details"', html)
        self.assertIn("Upper bound on paths retained per solve.", html)
        self.assertIn('aria-label="DeepMIMO Rx candidates details"', html)
        self.assertIn("Read-only estimate of receiver grid points before building filtering.", html)
        self.assertIn('aria-label="DeepMIMO building footprint filter details"', html)
        self.assertIn("Drops receiver candidates inside building footprint boxes before terrain projection.", html)
        self.assertIn(".modeMenuItem.active", css_source)
        self.assertIn(".deepMimoDatasetTray", css_source)
        self.assertIn(".deepMimoDatasetPanel", css_source)
        self.assertIn(".deepMimoDatasetDownload", css_source)
        self.assertNotIn(".deepMimoDownload{", css_source)
        self.assertNotIn(".deepMimoProgressTrack", css_source)


if __name__ == "__main__":
    unittest.main()
